### PR TITLE
Alpha diversity as sparse or on smaller dense tables

### PR DESCRIPTION
**Pull request by wasade**
Compute alpha metrics either directly from sparse data, or operate on partitions to minimize memory use on dense conversions. 

This PR is important as, at present, it takes 40GB to compute observed features on a table that contains 0.2GB of nonzero data.

### CODE REVIEW

**Comment by wasade** [comment]
Sorry about the failures, thought I had run all tests but skipped that rather important step. New commit momentarily

**Comment by lizgehret** [comment]
Hey @wasade looks like there were some merge conflicts - I went ahead and fixed those, since it was quick and easy. Pending successful CI, this should be in good shape! I'll do a final review after all tests pass.

**Comment by wasade** [comment]
Thanks!

**Review by lizgehret — APPROVED** [review]
lgtm, thanks @wasade!

**Pull request merged**
