### PR TITLE
Ports alpha, beta, and associated _phylogenetic calls to diversity-lib

### LINKED ISSUE #22: ENH: Provide dispatch functions for q2-diversity
**Improvement Description**
`diversity-lib` should provide functions that dispatch calls from `diversity alpha` and `diversity beta` to the best extant implementation of the selected measure.

### PR DESCRIPTION
**Pull request by ChrisKeefe**
Closes #22, required by https://github.com/qiime2/q2-diversity/issues/280
See also https://github.com/qiime2/q2-diversity/pull/281

f7fdb0c closes https://github.com/qiime2/q2-diversity/issues/286
bcec1c5 closes https://github.com/qiime2/q2-diversity/issues/288

### CODE REVIEW

**Comment by thermokarst** [comment]
Please see https://github.com/qiime2/q2-diversity/pull/281#issuecomment-665974036

**Comment by ChrisKeefe** [comment]
@thermokarst, I think this sucker's ready for review. There are one or two more tests I may write, but that shouldn't affect the rest of the PR.

**Comment by thermokarst** [comment]
Thanks @ChrisKeefe! Looks like you've got some merge conflicts - can you sort those out before I review? Thanks!

**Comment by ChrisKeefe** [comment]
@thermokarst, did you manually close this PR, or did the "Closes" keyword in #24 take care of it for us? Just curious. I've been tinkering with `Closes #<PR>` with mixed results, and if it worked here that would be a good data point.

**Comment by thermokarst** [comment]
The closing syntax closed it automatically.

**Pull request closed without merging**
